apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lms.fullname" . }}-backend
  labels:
    {{- include "lms.backend.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ include "lms.postgresql.host" . | quote }}
  REDIS_HOST: {{ include "lms.redis.host" . | quote }}
  FRONTEND_URL: {{ printf "%s://%s" (ternary "https" "http" .Values.ingress.tls.enabled) .Values.ingress.host | quote }}
  APP_URL: {{ printf "%s://%s/api" (ternary "https" "http" .Values.ingress.tls.enabled) .Values.ingress.host | quote }}
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
