## Staging overrides

backend:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  env:
    APP_ENV: staging
  persistence:
    size: 2Gi

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 192Mi

ingress:
  host: staging-lms.example.com
